[system]
compatible=platform-board
bootloader=uboot
mountprefix=/mnt/rauc

[keyring]
path=/etc/rauc/ca.cert.pem

[handlers]
pre-install=/usr/bin/rauc-pre-install.sh
post-install=/usr/bin/rauc-post-install.sh
