# layers/meta-distro/conf/machine/imx8mmevk.conf
#@TYPE: Machine
#@NAME: NXP i.MX8M Mini EVK
#@SOC: imx8mm
#@DESCRIPTION: Machine configuration for NXP i.MX8M Mini EVK

require conf/machine/include/imx-base.inc
require conf/machine/include/tune-cortexa53.inc

MACHINE = "imx8mmevk"

MACHINE_FEATURES += "rtc"

# Kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
KERNEL_DEVICETREE = "freescale/fsl-imx8mm-evk.dtb"

# U-Boot
UBOOT_MACHINE = "imx8mm_evk_config"
UBOOT_SUFFIX = "bin"

# Boot device
BOOT_SPACE = "65536"
IMAGE_BOOTLOADER = "imx-boot"

# Storage
SDCARD_ROOTFS_TYPE = "ext4"
