# layers/meta-distro/conf/machine/raspberrypi5.conf
#@TYPE: Machine
#@NAME: Raspberry Pi 5
#@SOC: bcm2712
#@DESCRIPTION: Machine configuration for Raspberry Pi 5

require conf/machine/include/arm/armv8a/tune-cortexa76.inc

MACHINE = "raspberrypi5"

# Include Raspberry Pi BSP
require inc/raspberrypi.inc
require inc/raspberrypi5.inc

MACHINE_FEATURES += "bluetooth wifi"

# Kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"
KERNEL_DEVICETREE = "broadcom/bcm2712-rpi-5-b.dtb"

# U-Boot
UBOOT_MACHINE = "rpi_arm64_config"
PREFERRED_PROVIDER_u-boot = "u-boot"

# Boot
RPI_USE_U_BOOT = "1"

# Serial console
SERIAL_CONSOLES = "115200;ttyAMA10"

# GPU memory
GPU_MEM = "76"
