# kas/dev/dev.yml
header:
  version: 12
  includes:
    - ../base.yml

machine: "qemux86-64"

local_conf_header:
  development: |
    # Development settings
    INHERIT += "rm_work"
    IMAGE_FSTYPES_DEBUG = "tar.bz2 ext3"
    USER_CLASSES += "buildstats buildhistory"
    
    # Debug symbols
    PACKAGE_DEBUG_SPLIT_STYLE = "debug-with-srcpkg"
    
    # Faster rebuilds
    BB_SERVER_TIMEOUT = "60"
